#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.af190a49.name = "Upgrade from 0.30.0"
    test_upgrade_from.40f44cd9834345bee80ed56cae16af1268fc129d.name = "Upgrade from 0.30.0~ynh11"
