#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=500M

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Install nodejs..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tmpdir=$(mktemp -d)
ynh_setup_source --dest_dir="$tmpdir"
pushd $tmpdir
    cp $install_dir/_h5ai/private/conf/options.json ./options.json.bkp
    npm ci
    npm run build
    ynh_safe_rm $install_dir/_h5ai
    mv build/_h5ai $install_dir/_h5ai
    cp ./options.json.bkp $install_dir/_h5ai/private/conf/options.json
popd
ynh_safe_rm $tmpdir

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:www-data "$install_dir"
chown -R $app:www-data "$install_dir/_h5ai"
chmod 700 "$install_dir/_h5ai/private/conf"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
